### ISSUE TITLE
Creacion de login

### ISSUE THREAD

**Issue by antoniio** [SistemasTecTlaxiaco/practica-de-mockup-y-front-end-mitte#2]
[Practica Mockup y front-end.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-mockup-y-front-end-mitte/files/6549036/Practica.Mockup.y.front-end.pdf)

**Comment by Nancy2050** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
